### ISSUE TITLE
SSL checks short-circuit to 'passed' after first check on same host

### ISSUE THREAD

**Issue by hamishfagg** [stepci/runner#105]
Because of session caching in the requests library, all stepCI SSL checks to the same host will always pass after the first one. This is because the call to `getPeerCertificate()` fails after the first request to a host, and stepCI then doesn't check the cert at all and falls back to default behaviour. Here is a minimal reproduction:

```js
import { run } from '@stepci/runner'
let workflow = {
  version: "1.1",
  name: "workflow_one",
  tests: {
    example: {
      steps: [{
        name: "step_1",
        http: {
          url: "https://www.google.com",
          method: "GET",
          check: {
            ssl: {
              valid: true,
              signed: true,
              daysUntilExpiration: [{
                  gte: 2000
              }]
            }
          }
        }
      }]
    }
  }
}

run(workflow).then(console.log)
await new Promise(r => setTimeout(r, 1000));
run(workflow).then(console.log)
```

If you run this the first test will fail (as it should, google's cert shouldn't be valid for 2000 days), but the same test will pass the second time around.

A solution to this is to supply got with an https agent with `maxCachedSessions` set to zero as seen here:
https://github.com/hamishfagg/runner/blob/bf73db7e17fa2035f9f829fb45e93c8a150df1e6/src/index.ts#L599-L622

With this the cert is always available, and can be checked for each request.

**Comment by mishushakov** [comment]
I had asked them about related SSL-cert problem some time ago

https://github.com/sindresorhus/got/issues/2153

**Comment by hamishfagg** [comment]
The closest thing I can find is `tlsSessionLifetime` in got, but I have tested that option and it does not fix this bug.

**Comment by mishushakov** [comment]
Sure, just wanted to check. Would you be able to send a PR with a modified http agent?
