### ISSUE TITLE
Add `regex` capture 

### ISSUE THREAD

**Issue by mishushakov** [stepci/runner#27]

**Comment by AndrewFarley** [comment]
@mishushakov There doesn't appear to be an example of how to use this, and I can't grok it from reading the source code.  Could you post some and perhaps code some test/examples and documentation into the docs repo either here or on stepci/stepci so we know how to use regex matching?

FYI: I'm looking to do a simple regex matching against the entire contents sent back.

**Comment by mishushakov** [comment]
the issue was about extracting data from body using regex, not matching
you can match the body against a regex using matchers

```
check:
  body: /^20/
```
