### ISSUE TITLE
Better variable parsing

### ISSUE THREAD

**Issue by mishushakov** [stepci/runner#33]
For details on this issue, see my comment: https://github.com/stepci/runner/issues/33#issuecomment-1275263630

**Comment by fmalk** [comment]
@mishushakov I took a look at that code (the line with `mustache.render`.
By "implement dot notation" you mean allow deeper properties of a captured object? Because it seems to me that code would only allow root properties, but the "captures" yaml element would allow a variable parsed from a deeper-level response, something like:

```
captures:
  id:
    jsonpath: $.level1.somearray[0].id
```

If that's already possible, I don't get what your suggestion was.

**Comment by mishushakov** [comment]
Thanks for checking out!
This issue is not related to captures. What we want to work on here is our variable parsing mechanism

Here's an example workflow where you see a variable being used (`{{env.host}}` in this example)

```yaml
version: "1.0"
name: Status Check
env:
  host: example.com
tests:
  example:
    steps:
      - name: GET request
        url: https://{{env.host}}
        method: GET
```

Currently, we convert the step object to string, replace the variables between `{{ }}` using mustache and then parse it back as JSON, using this code:

https://github.com/stepci/runner/blob/43b49bc8228e9f684989df9664e7977addc26260/src/index.ts#L395

This is sub-optimal and doesn't pass our quality control™

Now, let me give you an idea how we could solve this

Let's say we have this object:

```js
{
  hello: {
    world: "{{world.hello}}"
  }
}
```

We want to replace the template strings with values from the world object:

```js
{
  world: {
    hello: "Hello World"
  }
}
```

Using this pseudo-function:

```js
parseTemplate(helloObject, { worldObject })
```

Will turn into:

```js
{
  hello: {
    world: "Hello World"
  }
}
```

To access the variables by dot notation (eg. `world.hello`), you would have flatten the `worldObject` object using [flat](https://www.npmjs.com/package/flat) npm package

We could also consider different ways to implement this, maybe look how other projects have solved it
Let me know if you still have any questions. I'd be happy to help!

**Comment by fmalk** [comment]
@mishushakov I'll happily do a PR for this but I just want to be 100% clear on how to approach edge cases.

I don't think the `flat` package would be of much help in this scenario:

```
{
  hello: {
    world: "{{world.hello.again}}"
  }
}

{
  world: {
    hello: {
        again: "Hello again!"
    }
  }
}

// final result
{
  hello: {
    world: "Hello again!"
  }
}
```

But regardless of implementation, the end goal is to have nesting support, right? (and a cleaner code)

**Comment by mishushakov** [comment]
@fmalk We'd appreciate that! You can just try different approaches and leave a comment here

`flat` package should work in this case, it would turn this:

```js
{
  world: {
    hello: {
      again: "Hello again!"
    }
  }
}
```

Into this:

```js
const flatObject = {"world.hello.again": "Hello Again"}
```

Then you can say:

```js
flatObject["world.hello.again"]
```

**Comment by mishushakov** [comment]
The end goal is to be safer. You should only be able to use variables as a value!

**Comment by mishushakov** [comment]
@fmalk Hello, Fernando, do you have any progress you could share? Let me know if you need any help!

**Comment by mishushakov** [comment]
Mega!
